g = group.create(:name => 'virma', :password => 'virma')
l = lunch.create(:name => 'factory', :time => datetime.now, :group_id => g.id)
registration.create(:name => 'lalli', :lunch_id => l.id )
registration.create(:name => 'barbara', :lunch_id => l.id )
u = user.create(:username => 'lalli', :password => 'lalli')
usergroup.create(:group_id => g.id, :user_id => u.id)
